export const SET_PORTAL_CONFIGURATION = 'SET_PORTAL_CONFIGURATION';
export const SET_PORTAL_PAGES = 'SET_PORTAL_PAGES';
export const SET_RUNTIME_CONFIGURATION = 'SET_RUNTIME_CONFIGURATION';
export const ADD_APP_NOTIFICATION = 'ADD_APP_NOTIFICATION';
export const REMOVE_APP_NOTIFICATION = 'REMOVE_APP_NOTIFICATION';
export const CANCEL_EDIT = 'CANCEL_EDIT';
export const UPDATE_USER_PREFERENCE = 'UPDATE_USER_PREFERENCE';
export const REMOVE_USER_PREFERENCE = 'REMOVE_USER_PREFERENCE';