const beMeta = {
   id:"1400066",
   key:"General Information__QJx7sEqOEeqOZOqLd8MgeA",
   name:"General Information",
   bevName:"SupplierPortalView",
   maxColumns:2,
   configName:'abc',
   type:"Record Page",
   layout:{
       sections:[
         {
             id:"_miHxcF7sEeqsSvctAhViTw",
             displayIcon:"rectangle",
             containers:[
               {
                   id:"_miMC4F7sEeqsSvctAhViTw",
                   components:[
                     {
                         eClass:"http://www.informatica.com/mdm/config/model/v1#//BeFormComponent",
                         id:"_QIqhYEqOEeqOZOqLd8MgeA",
                         componentType:"BeFormComponent",
                         configName:"SupplierPortalView",
                         configType:"BEView",
                         beFormSections:[
                           {
                               id:"_QIs9oEqOEeqOZOqLd8MgeA",
                               key:" Company Information__QItksEqOEeqOZOqLd8MgeA",
                               name:" Company Information",
                               beFormFields:[
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QI0SYEqOEeqOZOqLd8MgeA",
                                     key:"fullNm__QI0SYUqOEeqOZOqLd8MgeA",
                                     name:"fullNm",
                                     fieldType:"textField",
                                     hierarchyName:"fullNm",
                                     required:true,
                                     isReadOnly:true,
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Company Legal Name",
                                     dataType:"String",
                                     length:100,
                                     trust:false,
                                     applyNullValues:false,
                                     displayFormat:"DATETIME_LONG_FORMAT",
                                     filterable:true,
                                     sortable:true
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QI0SYkqOEeqOZOqLd8MgeA",
                                     key:"dbaNm__QI0SY0qOEeqOZOqLd8MgeA",
                                     name:"dbaNm",
                                     fieldType:"textField",
                                     hierarchyName:"dbaNm",
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Doing Business As",
                                     dataType:"String",
                                     length:100,
                                     required:false,
                                     trust:false,
                                     applyNullValues:false,
                                     displayFormat:"DATETIME_LONG_FORMAT",
                                     filterable:true,
                                     sortable:true
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QI38wEqOEeqOZOqLd8MgeA",
                                     key:"DunsNumber__QI38wUqOEeqOZOqLd8MgeA",
                                     name:"DunsNumber",
                                     fieldType:"textField",
                                     hierarchyName:"DunsNumber",
                                     required:true,
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"D-U-N-S",
                                     dataType:"String",
                                     length:50,
                                     trust:false,
                                     applyNullValues:false,
                                     displayFormat:"DATETIME_LONG_FORMAT",
                                     filterable:true,
                                     sortable:true
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QI5K4EqOEeqOZOqLd8MgeA",
                                     key:"TaxId__QI5K4UqOEeqOZOqLd8MgeA",
                                     name:"TaxId",
                                     fieldType:"textField",
                                     hierarchyName:"TaxId",
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Tax ID",
                                     dataType:"String",
                                     length:50,
                                     required:false,
                                     trust:false,
                                     applyNullValues:false,
                                     displayFormat:"DATETIME_LONG_FORMAT",
                                     filterable:true,
                                     sortable:true
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QI5x8EqOEeqOZOqLd8MgeA",
                                     key:"yrOfEstblshmnt__QI5x8UqOEeqOZOqLd8MgeA",
                                     name:"yrOfEstblshmnt",
                                     fieldType:"",
                                     hierarchyName:"yrOfEstblshmnt",
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Established In",
                                     dataType:"Integer",
                                     length:38,
                                     required:false,
                                     trust:false,
                                     applyNullValues:false,
                                     displayFormat:"DATETIME_LONG_FORMAT",
                                     filterable:true,
                                     sortable:true
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QI6ZAEqOEeqOZOqLd8MgeA",
                                     key:"numOfEmp__QI6ZAUqOEeqOZOqLd8MgeA",
                                     name:"numOfEmp",
                                     fieldType:"",
                                     hierarchyName:"numOfEmp",
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Number of Employees",
                                     dataType:"Integer",
                                     length:38,
                                     required:false,
                                     trust:false,
                                     applyNullValues:false,
                                     displayFormat:"DATETIME_LONG_FORMAT",
                                     filterable:true,
                                     sortable:true
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QI7AEEqOEeqOZOqLd8MgeA",
                                     key:"countryOfIncorporation__QI7AEUqOEeqOZOqLd8MgeA",
                                     name:"countryOfIncorporation",
                                     fieldType:"dropdown",
                                     hierarchyName:"countryOfIncorporation",
                                     required:true,
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Country of Incorporation",
                                     dataType:"lookup",
                                     readOnly:false,
                                     system:false,
                                     trust:false,
                                     applyNullValues:false,
                                     filterable:true,
                                     sortable:true,
                                     lookup:{
                                        link:[
                                          {
                                              href:"http://localhost:8080/cmx/lookup/localhost-orcl-SUPPLIER_ORS/id-label/SupplierPortalView/countryOfIncorporation",
                                              rel:"lookup"
                                          },
                                          {
                                              href:"http://localhost:8080/cmx/lookup/localhost-orcl-SUPPLIER_ORS/object/SupplierPortalView/countryOfIncorporation",
                                              rel:"list"
                                          }
                                       ],
                                        object:"LookupCountry",
                                        key:"countryCode",
                                        value:"countryDesc"
                                    }
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QI_RgEqOEeqOZOqLd8MgeA",
                                     key:"ownrshpTyp__QI_RgUqOEeqOZOqLd8MgeA",
                                     name:"ownrshpTyp",
                                     fieldType:"dropdown",
                                     hierarchyName:"ownrshpTyp",
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Company Ownership",
                                     dataType:"lookup",
                                     readOnly:false,
                                     required:false,
                                     system:false,
                                     trust:false,
                                     applyNullValues:false,
                                     filterable:true,
                                     sortable:true,
                                     lookup:{
                                        link:[
                                          {
                                              href:"http://localhost:8080/cmx/lookup/localhost-orcl-SUPPLIER_ORS/id-label/SupplierPortalView/ownrshpTyp",
                                              rel:"lookup"
                                          },
                                          {
                                              href:"http://localhost:8080/cmx/lookup/localhost-orcl-SUPPLIER_ORS/object/SupplierPortalView/ownrshpTyp",
                                              rel:"list"
                                          }
                                       ],
                                        object:"LookupOwnershipType",
                                        key:"ownershipTypeCode",
                                        value:"ownershipTypeDesc"
                                    }
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QJAfoEqOEeqOZOqLd8MgeA",
                                     key:"lglFrm__QJAfoUqOEeqOZOqLd8MgeA",
                                     name:"lglFrm",
                                     fieldType:"dropdown",
                                     hierarchyName:"lglFrm",
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Legal Structure",
                                     dataType:"lookup",
                                     readOnly:false,
                                     required:false,
                                     system:false,
                                     trust:false,
                                     applyNullValues:false,
                                     filterable:true,
                                     sortable:true,
                                     lookup:{
                                        link:[
                                          {
                                              href:"http://localhost:8080/cmx/lookup/localhost-orcl-SUPPLIER_ORS/id-label/SupplierPortalView/lglFrm",
                                              rel:"lookup"
                                          },
                                          {
                                              href:"http://localhost:8080/cmx/lookup/localhost-orcl-SUPPLIER_ORS/object/SupplierPortalView/lglFrm",
                                              rel:"list"
                                          }
                                       ],
                                        object:"LookupLegalForm",
                                        key:"legalFormCode",
                                        value:"legalFormDesc"
                                    }
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QJBGsEqOEeqOZOqLd8MgeA",
                                     key:"bsnsTyp__QJBGsUqOEeqOZOqLd8MgeA",
                                     name:"bsnsTyp",
                                     fieldType:"dropdown",
                                     hierarchyName:"bsnsTyp",
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Business Type",
                                     dataType:"lookup",
                                     readOnly:false,
                                     required:false,
                                     system:false,
                                     trust:false,
                                     applyNullValues:false,
                                     filterable:true,
                                     sortable:true,
                                     lookup:{
                                        link:[
                                          {
                                              href:"http://localhost:8080/cmx/lookup/localhost-orcl-SUPPLIER_ORS/id-label/SupplierPortalView/bsnsTyp",
                                              rel:"lookup"
                                          },
                                          {
                                              href:"http://localhost:8080/cmx/lookup/localhost-orcl-SUPPLIER_ORS/object/SupplierPortalView/bsnsTyp",
                                              rel:"list"
                                          }
                                       ],
                                        object:"LookupBusinessType",
                                        key:"businessTypeCode",
                                        value:"businessTypeDesc"
                                    }
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QJBtwEqOEeqOZOqLd8MgeA",
                                     key:"tckrSymbl__QJBtwUqOEeqOZOqLd8MgeA",
                                     name:"tckrSymbl",
                                     fieldType:"textField",
                                     hierarchyName:"tckrSymbl",
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Stock Symbol",
                                     dataType:"String",
                                     length:50,
                                     required:false,
                                     trust:false,
                                     applyNullValues:false,
                                     displayFormat:"DATETIME_LONG_FORMAT",
                                     filterable:true,
                                     sortable:true
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QJC74EqOEeqOZOqLd8MgeA",
                                     key:"onlnSellFlg__QJC74UqOEeqOZOqLd8MgeA",
                                     name:"onlnSellFlg",
                                     fieldType:"radioButton",
                                     hierarchyName:"onlnSellFlg",
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"E-Business Ready",
                                     dataType:"Boolean",
                                     length:0,
                                     totalDigits:0,
                                     fractionDigits:0,
                                     trust:false,
                                     applyNullValues:false,
                                     filterable:false,
                                     sortable:false,
                                     required:false
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QJDi8EqOEeqOZOqLd8MgeA",
                                     key:"websiteURL__QJDi8UqOEeqOZOqLd8MgeA",
                                     name:"websiteURL",
                                     fieldType:"textField",
                                     hierarchyName:"websiteURL",
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Website URL",
                                     dataType:"String",
                                     length:50,
                                     required:false,
                                     trust:false,
                                     applyNullValues:false,
                                     displayFormat:"DATETIME_LONG_FORMAT",
                                     filterable:true,
                                     sortable:true
                                 },
                                 {
                                     configName:"SupplierPortalView",
                                     configType:"BEView",
                                     id:"_QJEKAEqOEeqOZOqLd8MgeA",
                                     key:"facebook__QJEKAUqOEeqOZOqLd8MgeA",
                                     name:"facebook",
                                     fieldType:"textField",
                                     hierarchyName:"facebook",
                                     operations:{
                                        read:{
                                           allowed:true
                                       },
                                        create:{
                                           allowed:true
                                       },
                                        update:{
                                           allowed:true
                                       }
                                    },
                                     label:"Facebook",
                                     dataType:"String",
                                     length:60,
                                     required:false,
                                     trust:false,
                                     applyNullValues:false,
                                     displayFormat:"DATETIME_LONG_FORMAT",
                                     filterable:true,
                                     sortable:true
                                 }
                              ]
                           }
                        ],
                         operations:{
                            read:{
                               allowed:true
                           },
                            search:{
                               allowed:true
                           },
                            create:{
                               allowed:true
                           },
                            update:{
                               allowed:true,
                               task:{
                                  template:{
                                     title:"Review Changes For {taskRecord[0].label}",
                                     priority:"NORMAL",
                                     dueDate:"2021-01-25T19:10:26.309+05:30",
                                     taskType:"AVOSBeDraftState"
                                 },
                                  comment:"AS_REQUIRED",
                                  attachment:"OPTIONAL"
                              }
                           },
                            merge:{
                               allowed:false
                           },
                            delete:{
                               allowed:true
                           },
                            unmerge:{
                               allowed:false
                           }
                        },
                         objectType:"ENTITY",
                         timeline:false,
                         viewOf:"Supplier",
                         required:false
                     }
                  ],
                   style:{
                      width:1
                  }
               }
            ],
             sectionType:"Section-Type 1"
         }
      ]
   },
   order:5,
   states:[
       "Approved"
   ],
   roles:[
       "Supplier Administrators",
       "Supplier Users"
   ]
}


export {beMeta};