export const beFormFields = [
    {
        name: "cmpnyLglNm",
        label: "Company Legal Name",
        required: true,
        hierarchyName: "cmpnyLglNm",
        many: false,
        dataType: "String",
    },
    {
        name: "cmpnyStrtAdd",
        label: "Company Street Address",
        required: true,
        hierarchyName: "cmpnyStrtAdd",
        many: false,
        dataType: "String",
    },
    {
        name: "country",
        label: "Country",
        required: true,
        hierarchyName: "country",
        many: false,
        dataType: "lookup",
    },
    {
        name: "portalAssc",
        label: "Portal Association",
        required: false,
        hierarchyName: "portalAssc",
        many: false,
        dataType: "lookup",
    },
    {
        name: "prtlState",
        label: "Portal State",
        required: false,
        hierarchyName: "prtlState",
        many: false,
        dataType: "String",
    },
    {
        name: "pstlCd",
        label: "Zip/Postal Code",
        required: false,
        hierarchyName: "pstlCd",
        many: false,
        dataType: "String",
    },
    {
        name: "state",
        label: "State/Province",
        required: false,
        hierarchyName: "state",
        many: false,
        dataType: "lookup",
    },
    {
        name: "Contact",
        label: "Contact",
        many: true,
        hierarchyName: "Contact",
        beFormFields: [
            {
                name: "emailAdd",
                label: "Email Address",
                required: false,
                hierarchyName: "Contact.emailAdd",
                many: false,
                dataType: "String",
            },
            {
                name: "frstNm",
                label: "First Name",
                required: true,
                hierarchyName: "Contact.frstNm",
                many: false,
                dataType: "String",
            },
            {
                name: "hmRelTypCd",
                label: "Relationship Type",
                required: false,
                hierarchyName: "Contact.hmRelTypCd",
                many: false,
                dataType: "lookup",
            },
            {
                name: "lstNm",
                label: "Last Name",
                required: true,
                hierarchyName: "Contact.lstNm",
                many: false,
                dataType: "String",
            },
            {
                name: "phnDlngCd",
                label: "Phone Dialing Code",
                required: false,
                hierarchyName: "Contact.phnDlngCd",
                many: false,
                dataType: "String",
            },
            {
                name: "phnNum",
                label: "Phone Number",
                required: false,
                hierarchyName: "Contact.phnNum",
                many: false,
                dataType: "String",
            },
            {
                name: "prtlUsrInd",
                label: "Portal User Indicator",
                hierarchyName: "Contact.prtlUsrInd",
                many: false,
                dataType: "Boolean",
            },
            {
                name: "prtlUsrNm",
                label: "Portal User Name",
                required: false,
                hierarchyName: "Contact.prtlUsrNm",
                many: false,
                dataType: "String",
            },
            {
                name: "prtlUsrRle",
                label: "Portal User Role",
                required: false,
                hierarchyName: "Contact.prtlUsrRle",
                many: false,
                dataType: "lookup",
            },
            {
                name: "title",
                label: "Title",
                required: false,
                hierarchyName: "Contact.title",
                many: false,
                dataType: "String",
            }
        ]
    }
];

export const selectedBeFormFields = {
    beFormFields: [{
        attributeSelector: undefined,
        configName: "CustomerOrgRegistrationView",
        configType: "BEView",
        fieldType: "textField",
        hierarchyName: "cmpnyLglNm",
        many: false,
        metadata: {
            attributeSelector: undefined,
            dataType: "String",
            hierarchyName: "cmpnyLglNm",
            label: "Company Legal Name",
            many: false,
            name: "cmpnyLglNm",
            readOnly: undefined,
            required: true
        },
        name: "cmpnyLglNm",
        required: true
    },
    {
        attributeSelector: undefined,
        configName: "CustomerOrgRegistrationView",
        configType: "BEView",
        fieldType: "textField",
        hierarchyName: "cmpnyStrtAdd",
        many: false,
        metadata: {
            attributeSelector: undefined,
            dataType: "String",
            hierarchyName: "cmpnyStrtAdd",
            label: "Company Street Address",
            many: false,
            name: "cmpnyStrtAdd",
            readOnly: undefined,
            required: true
        },
        name: "cmpnyStrtAdd",
        required: true
    },
    {
        attributeSelector: undefined,
        configName: "CustomerOrgRegistrationView",
        configType: "BEView",
        fieldType: "dropdown",
        hierarchyName: "country",
        many: false,
        metadata: {
            attributeSelector: undefined,
            dataType: "lookup",
            hierarchyName: "country",
            label: "Country",
            many: false,
            name: "country",
            readOnly: undefined,
            required: true
        },
        name: "country",
        required: true
    },
    {
        attributeSelector: undefined,
        configName: "CustomerOrgRegistrationView",
        configType: "BEView",
        fieldType: "dropdown",
        hierarchyName: "portalAssc",
        many: false,
        metadata: {
            attributeSelector: undefined,
            dataType: "lookup",
            hierarchyName: "portalAssc",
            label: "Portal Association",
            many: false,
            name: "portalAssc",
            readOnly: undefined,
            required: false
        },
        name: "portalAssc",
        required: false
    },
    {
        attributeSelector: undefined,
        configName: "CustomerOrgRegistrationView",
        configType: "BEView",
        fieldType: "textField",
        hierarchyName: "prtlState",
        many: false,
        metadata: {
            attributeSelector: undefined,
            dataType: "String",
            hierarchyName: "prtlState",
            label: "Portal State",
            many: false,
            name: "prtlState",
            readOnly: undefined,
            required: false
        },
        name: "prtlState",
        required: false
    },
    {
        attributeSelector: undefined,
        configName: "CustomerOrgRegistrationView",
        configType: "BEView",
        fieldType: "textField",
        hierarchyName: "pstlCd",
        many: false,
        metadata: {
            attributeSelector: undefined,
            dataType: "String",
            hierarchyName: "pstlCd",
            label: "Zip/Postal Code",
            many: false,
            name: "pstlCd",
            readOnly: undefined,
            required: false
        },
        name: "pstlCd",
        required: false
    },
    {
        attributeSelector: undefined,
        configName: "CustomerOrgRegistrationView",
        configType: "BEView",
        fieldType: "dropdown",
        hierarchyName: "state",
        many: false,
        metadata: {
            attributeSelector: undefined,
            dataType: "lookup",
            hierarchyName: "state",
            label: "State/Province",
            many: false,
            name: "state",
            readOnly: undefined,
            required: false
        },
        name: "state",
        required: false
    },
    {
        attributeSelector: undefined,
        beFormFields: [{
            attributeSelector: undefined,
            configName: "CustomerOrgRegistrationView",
            configType: "BEView",
            fieldType: "textField",
            hierarchyName: "Contact.emailAdd",
            many: false,
            metadata: {
                attributeSelector: undefined,
                dataType: "String",
                hierarchyName: "Contact.emailAdd",
                label: "Email Address",
                lookup: undefined,
                many: false,
                name: "emailAdd",
                readOnly: undefined,
                required: false
            },
            name: "emailAdd",
            required: false
        },
        {
            attributeSelector: undefined,
            configName: "CustomerOrgRegistrationView",
            configType: "BEView",
            fieldType: "textField",
            hierarchyName: "Contact.frstNm",
            many: false,
            metadata: {
                attributeSelector: undefined,
                dataType: "String",
                hierarchyName: "Contact.frstNm",
                label: "First Name",
                lookup: undefined,
                many: false,
                name: "frstNm",
                readOnly: undefined,
                required: true
            },
            name: "frstNm",
            required: true
        },
        {
            attributeSelector: undefined,
            configName: "CustomerOrgRegistrationView",
            configType: "BEView",
            fieldType: "dropdown",
            hierarchyName: "Contact.hmRelTypCd",
            many: false,
            metadata: {
                attributeSelector: undefined,
                dataType: "lookup",
                hierarchyName: "Contact.hmRelTypCd",
                label: "Relationship Type",
                many: false,
                name: "hmRelTypCd",
                readOnly: undefined,
                required: false
            },
            name: "hmRelTypCd",
            required: false
        },
        {
            attributeSelector: undefined,
            configName: "CustomerOrgRegistrationView",
            configType: "BEView",
            fieldType: "textField",
            hierarchyName: "Contact.lstNm",
            many: false,
            metadata: {
                attributeSelector: undefined,
                dataType: "String",
                hierarchyName: "Contact.lstNm",
                label: "Last Name",
                lookup: undefined,
                many: false,
                name: "lstNm",
                readOnly: undefined,
                required: true
            },
            name: "lstNm",
            required: true
        },
        {
            attributeSelector: undefined,
            configName: "CustomerOrgRegistrationView",
            configType: "BEView",
            fieldType: "textField",
            hierarchyName: "Contact.phnDlngCd",
            many: false,
            metadata: {
                attributeSelector: undefined,
                dataType: "String",
                hierarchyName: "Contact.phnDlngCd",
                label: "Phone Dialing Code",
                lookup: undefined,
                many: false,
                name: "phnDlngCd",
                readOnly: undefined,
                required: false
            },
            name: "phnDlngCd",
            required: false
        },
        {
            attributeSelector: undefined,
            configName: "CustomerOrgRegistrationView",
            configType: "BEView",
            fieldType: "textField",
            hierarchyName: "Contact.phnNum",
            many: false,
            metadata: {
                attributeSelector: undefined,
                dataType: "String",
                hierarchyName: "Contact.phnNum",
                label: "Phone Number",
                lookup: undefined,
                many: false,
                name: "phnNum",
                readOnly: undefined,
                required: false
            },
            name: "phnNum",
            required: false
        },
        {
            attributeSelector: undefined,
            configName: "CustomerOrgRegistrationView",
            configType: "BEView",
            fieldType: "radioButton",
            hierarchyName: "Contact.prtlUsrInd",
            many: false,
            metadata: {
                attributeSelector: undefined,
                dataType: "Boolean",
                hierarchyName: "Contact.prtlUsrInd",
                label: "Portal User Indicator",
                lookup: undefined,
                many: false,
                name: "prtlUsrInd",
                readOnly: undefined,
                required: undefined
            },
            name: "prtlUsrInd",
            required: false
        },
        {
            attributeSelector: undefined,
            configName: "CustomerOrgRegistrationView",
            configType: "BEView",
            fieldType: "textField",
            hierarchyName: "Contact.prtlUsrNm",
            many: false,
            metadata: {
                attributeSelector: undefined,
                dataType: "String",
                hierarchyName: "Contact.prtlUsrNm",
                label: "Portal User Name",
                lookup: undefined,
                many: false,
                name: "prtlUsrNm",
                readOnly: undefined,
                required: false
            },
            name: "prtlUsrNm",
            required: false
        },
        {
            attributeSelector: undefined,
            configName: "CustomerOrgRegistrationView",
            configType: "BEView",
            fieldType: "dropdown",
            hierarchyName: "Contact.prtlUsrRle",
            many: false,
            metadata: {
                attributeSelector: undefined,
                dataType: "lookup",
                hierarchyName: "Contact.prtlUsrRle",
                label: "Portal User Role",
                lookup: undefined,
                many: false,
                name: "prtlUsrRle",
                readOnly: undefined,
                required: false
            },
            name: "prtlUsrRle",
            required: false
        },
        {
            attributeSelector: undefined,
            configName: "CustomerOrgRegistrationView",
            configType: "BEView",
            fieldType: "textField",
            hierarchyName: "Contact.title",
            many: false,
            metadata: {
                attributeSelector: undefined,
                dataType: "String",
                hierarchyName: "Contact.title",
                label: "Title",
                lookup: undefined,
                many: false,
                name: "title",
                readOnly: undefined,
                required: false
            },
            name: "title",
            required: false
        }],
        configName: "CustomerOrgRegistrationView",
        configType: "BEView",
        enableValidation: false,
        fieldType: "cardView",
        hierarchyName: "Contact",
        many: true,
        metadata: {
            attributeSelector: undefined,
            dataType: undefined,
            hierarchyName: "Contact",
            label: "Contact",
            lookup: undefined,
            many: true,
            name: "Contact",
            readOnly: undefined,
            required: undefined
        },
        name: "Contact"
    }],
    hideName: false,
    name: "",
    order: 0
};
