package com.informatica.mdm.portal.metadata.util;

import org.apache.commons.lang3.StringUtils;

public class DatabaseConstants {

	public static final String COLUMN_PORTAL_ID = "PORTAL_ID";
    public static final String COLUMN_APP_ID = "APP_ID";
    public static final String COLUMN_APP_TYPE = "APP_TYPE";
    public static final String COLUMN_OWNER = "OWNER";
    public static final String COLUMN_USER_PREFERENCE = "USER_PREFERENCE";
	public static final String COLUMN_PORTAL_NAME = "PORTAL_NAME";
	public static final String COLUMN_LAST_UPDATED_DATE = "LAST_UPDATED_DATE";
	public static final String COLUMN_LAST_UPDATED_BY = "LAST_UPDATED_BY";
	public static final String COLUMN_CREATED_DATE = "CREATED_DATE";
	public static final String COLUMN_CREATED_BY = "CREATED_BY";
	public static final String COLUMN_CONFIGURATION = "CONFIGURATION";
	public static final String COLUMN_BUNDLE_PROPERTIES = "BUNDLE_PROPERTIES";
	public static final String COLUMN_ERROR_PROPERTIES = "ERROR_PROPERTIES";
	public static final String COLUMN_RUNTIME_CONFIGURATION = "RUNTIME_CONFIGURATION";
    public static final String COLUMN_SSO_CONFIGURATION = "SSO_CONFIGURATION";
	public static final String COLUMN_PORTAL_STATUS = "PORTAL_STATUS";
	public static final String COLUMN_PORTAL_METAMODEL_VERSION = "METAMODEL_VERSION";
	public static final String TABLE_PORTAL_CONFIG = "C_SOLUTIONS_PORTAL_CONFIG";
	public static final String TABLE_PORTAL_CONFIG_TEMP = "C_SOLUTIONS_PORTAL_CONFIG_TEMP";
    public static final String TABLE_USER_PREFERENCE = "C_SOLUTIONS_USER_PREFERENCE";
	public static final String PORTAL_CONFIG_ENUM = "PORTAL_CONFIG";
	public static final String PORTAL_CONFIG_TEMP_ENUM = "PORTAL_CONFIG_CACHE";
	public static final String TABLE_ROLES = "C_REPOS_SAM_ROLE";
	public static final String TABLE_PORTAL_ASSC = "C_BT_INFA_PRTL_ASSC";
	public static final String COLUMN_ASSC_PORTAL_ID= "PRTL_ID";
	public static final String COLUMN_ASSC_PORTAL_NAME = "PRTL_NM";
	public static final String COLUMN_ASSC_PORTAL_BE_NAME = "BE_NM";
	public static final String COLUMN_ROWID_OBJECT = "ROWID_OBJECT";
	
	public static final String COLUMN_VERSION = "VERSION";
	public static final String COLUMN_BASE_VERSION = "BASE_VERSION";
	public static final String COLUMN_USER_NAME = "USERNAME";
	
	public static final String COLUMN_ROLE_NAME = "ROLE_NAME";
	
	public static final String TABLE_FORGOT_PASSWORD_LINK_EXPIRY = "C_SOLUTIONS_PASSWORD_EXPIRY";
	public static final String COLUMN_USER_ID = "USER_ID";
	public static final String COLUMN_HASH_VALUE = "HASH_VALUE";
	public static final String COLUMN_MILLISEC = "MILISEC";
	public static final String COLUMN_EMAIL_ID = "EMAIL_ID";
	
	public static final String QUERY_CREATE_USER_PORTAL_ENTITY_ORACLE = StringUtils.join(
			"CREATE TABLE ", TABLE_PORTAL_CONFIG_TEMP, 
			" (",COLUMN_PORTAL_ID, " NUMBER(20) NOT NULL, ",
			COLUMN_PORTAL_NAME, " VARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_BY, " VARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_DATE, " TIMESTAMP (6), ",
			COLUMN_LAST_UPDATED_BY, " VARCHAR(250) NOT NULL, ",
			COLUMN_LAST_UPDATED_DATE, " TIMESTAMP (6), ",
			COLUMN_VERSION, " NUMBER(20) NOT NULL, ",
			COLUMN_BASE_VERSION, " VARCHAR(250) NOT NULL, ",
			COLUMN_USER_NAME, " VARCHAR(250) NOT NULL, ",
			"CONSTRAINT PK_PORTAL_CACHE PRIMARY KEY (",COLUMN_PORTAL_ID,", ", COLUMN_USER_NAME,"), ",
			COLUMN_RUNTIME_CONFIGURATION, " BLOB, ",
			COLUMN_SSO_CONFIGURATION, " BLOB, ",
			COLUMN_CONFIGURATION, " BLOB NOT NULL, ",
			COLUMN_ERROR_PROPERTIES, " BLOB, ",
			COLUMN_BUNDLE_PROPERTIES, " BLOB )"
		);
	
	public static final String QUERY_CREATE_PORTAL_ENTITY_ORACLE = StringUtils.join(
			"CREATE TABLE ", TABLE_PORTAL_CONFIG, 
			" (",COLUMN_PORTAL_ID, " NUMBER(20) NOT NULL, ",
			COLUMN_PORTAL_NAME, " VARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_BY, " VARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_DATE, " TIMESTAMP (6), ",
			COLUMN_LAST_UPDATED_BY, " VARCHAR(250) NOT NULL, ",
			COLUMN_LAST_UPDATED_DATE, " TIMESTAMP (6), ",
			COLUMN_VERSION, " NUMBER(20) NOT NULL, ",
			"CONSTRAINT PK_PORTAL PRIMARY KEY (",COLUMN_PORTAL_ID,"), ",
			COLUMN_RUNTIME_CONFIGURATION, " BLOB, ",
            COLUMN_SSO_CONFIGURATION, " BLOB, ",
			COLUMN_CONFIGURATION, " BLOB NOT NULL, ",
			COLUMN_PORTAL_STATUS, " VARCHAR(25) NOT NULL, ",
			COLUMN_PORTAL_METAMODEL_VERSION, " VARCHAR(50), ",
			COLUMN_ERROR_PROPERTIES, " BLOB, ",
			COLUMN_BUNDLE_PROPERTIES, " BLOB )"
		);
	
	
	public static final String QUERY_CREATE_USER_PORTAL_ENTITY_MSSQL = StringUtils.join(
			"CREATE TABLE ", TABLE_PORTAL_CONFIG_TEMP, 
			" (",COLUMN_PORTAL_ID, " BIGINT NOT NULL, ",
			COLUMN_PORTAL_NAME, " nVARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_BY, " nVARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_DATE, " DATETIME, ",
			COLUMN_LAST_UPDATED_BY, " nVARCHAR(250) NOT NULL, ",
			COLUMN_LAST_UPDATED_DATE, " DATETIME, ",
			COLUMN_VERSION, " BIGINT NOT NULL, ",
			COLUMN_BASE_VERSION, " nVARCHAR(250) NOT NULL, ",
			COLUMN_USER_NAME, " nVARCHAR(250) NOT NULL, ",
			"CONSTRAINT PK_PORTAL_CACHE PRIMARY KEY (",COLUMN_PORTAL_ID,", ", COLUMN_USER_NAME,"), ",
			COLUMN_RUNTIME_CONFIGURATION, " VARBINARY(MAX), ",
			COLUMN_SSO_CONFIGURATION, " VARBINARY(MAX), ",
			COLUMN_CONFIGURATION, " VARBINARY(MAX) NOT NULL, ",
			COLUMN_ERROR_PROPERTIES, " VARBINARY(MAX), ",
			COLUMN_BUNDLE_PROPERTIES, " VARBINARY(MAX) )"
		);
	
	public static final String QUERY_CREATE_PORTAL_ENTITY_MSSQL = StringUtils.join(
			"CREATE TABLE ", TABLE_PORTAL_CONFIG, 
			" (",COLUMN_PORTAL_ID, " BIGINT NOT NULL, ",
			COLUMN_PORTAL_NAME, " nVARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_BY, " nVARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_DATE, " DATETIME, ",
			COLUMN_LAST_UPDATED_BY, " nVARCHAR(250) NOT NULL, ",
			COLUMN_LAST_UPDATED_DATE, " DATETIME, ",
			COLUMN_VERSION, " BIGINT NOT NULL, ",
			"CONSTRAINT PK_PORTAL PRIMARY KEY (",COLUMN_PORTAL_ID,"), ",
			COLUMN_RUNTIME_CONFIGURATION, " VARBINARY(MAX), ",
            COLUMN_SSO_CONFIGURATION, " VARBINARY(MAX), ",
			COLUMN_CONFIGURATION, " VARBINARY(MAX) NOT NULL, ",
			COLUMN_PORTAL_STATUS, " nVARCHAR(25) NOT NULL, ",
			COLUMN_PORTAL_METAMODEL_VERSION, " nVARCHAR(25), ",
			COLUMN_ERROR_PROPERTIES, " VARBINARY(MAX), ",
			COLUMN_BUNDLE_PROPERTIES, " VARBINARY(MAX) )"
		);
	
	public static final String QUERY_CREATE_PASSWORD_EXPIRY_ORACLE = StringUtils.join(
			"CREATE TABLE ", TABLE_FORGOT_PASSWORD_LINK_EXPIRY, 
			" (",COLUMN_USER_ID, " VARCHAR(100) NOT NULL, ",
			COLUMN_HASH_VALUE, " VARCHAR(200) NOT NULL, ",
			COLUMN_MILLISEC, " VARCHAR(20), ",
			COLUMN_EMAIL_ID, " VARCHAR(100) )" 
		);
	
	public static final String QUERY_CREATE_PASSWORD_EXPIRY_MSSQL = StringUtils.join(
			"CREATE TABLE ", TABLE_FORGOT_PASSWORD_LINK_EXPIRY, 
			" (",COLUMN_USER_ID, " nVARCHAR(100) NOT NULL, ",
			COLUMN_HASH_VALUE, " nVARCHAR(200) NOT NULL, ",
			COLUMN_MILLISEC, " nVARCHAR(20), ",
			COLUMN_EMAIL_ID, " nVARCHAR(100) )"
		);
	
	
	public static final String QUERY_CREATE_USER_PORTAL_ENTITY_DB2 = StringUtils.join(
			"CREATE TABLE ", TABLE_PORTAL_CONFIG_TEMP, 
			" (",COLUMN_PORTAL_ID, " DECIMAL(20) NOT NULL, ",
			COLUMN_PORTAL_NAME, " VARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_BY, " VARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_DATE, " TIMESTAMP (6), ",
			COLUMN_LAST_UPDATED_BY, " VARCHAR(250) NOT NULL, ",
			COLUMN_LAST_UPDATED_DATE, " TIMESTAMP (6), ",
			COLUMN_VERSION, " DECIMAL(20) NOT NULL, ",
			COLUMN_BASE_VERSION, " VARCHAR(250) NOT NULL, ",
			COLUMN_USER_NAME, " VARCHAR(250) NOT NULL, ",
			"CONSTRAINT PK_PORTAL_CACHE PRIMARY KEY (",COLUMN_PORTAL_ID,", ", COLUMN_USER_NAME,"), ",
			COLUMN_RUNTIME_CONFIGURATION, " BLOB, ",
			COLUMN_SSO_CONFIGURATION, " BLOB, ",
			COLUMN_CONFIGURATION, " BLOB NOT NULL, ",
			COLUMN_ERROR_PROPERTIES, " BLOB, ",
			COLUMN_BUNDLE_PROPERTIES, " BLOB )"
		);
	
	public static final String QUERY_CREATE_PORTAL_ENTITY_DB2 = StringUtils.join(
			"CREATE TABLE ", TABLE_PORTAL_CONFIG, 
			" (",COLUMN_PORTAL_ID, " DECIMAL(20) NOT NULL, ",
			COLUMN_PORTAL_NAME, " VARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_BY, " VARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_DATE, " TIMESTAMP (6), ",
			COLUMN_LAST_UPDATED_BY, " VARCHAR(250) NOT NULL, ",
			COLUMN_LAST_UPDATED_DATE, " TIMESTAMP (6), ",
			COLUMN_VERSION, " DECIMAL(20) NOT NULL, ",
			"CONSTRAINT PK_PORTAL PRIMARY KEY (",COLUMN_PORTAL_ID,"), ",
			COLUMN_RUNTIME_CONFIGURATION, " BLOB, ",
            COLUMN_SSO_CONFIGURATION, " BLOB, ",
			COLUMN_CONFIGURATION, " BLOB NOT NULL, ",
			COLUMN_PORTAL_STATUS, " VARCHAR(25) NOT NULL, ",
			COLUMN_PORTAL_METAMODEL_VERSION, " VARCHAR(25), ",
			COLUMN_ERROR_PROPERTIES, " BLOB, ",
			COLUMN_BUNDLE_PROPERTIES, " BLOB )"
		);

    public static final String QUERY_CREATE_USER_PREFERENCE_ORACLE = StringUtils.join(
            "CREATE TABLE ", TABLE_USER_PREFERENCE,
            " (",COLUMN_APP_TYPE, " VARCHAR(250) NOT NULL, ",
			COLUMN_APP_ID, " NUMBER(20) NOT NULL, ",
            COLUMN_OWNER, " VARCHAR(250) NOT NULL, ",
            COLUMN_CREATED_DATE, " TIMESTAMP (6), ",
            COLUMN_LAST_UPDATED_DATE, " TIMESTAMP (6), ",
            "CONSTRAINT PK_PORTAL_USER_PREFERENCE PRIMARY KEY (",COLUMN_APP_ID,", ", COLUMN_APP_TYPE,", ", COLUMN_OWNER,"), ",
            COLUMN_USER_PREFERENCE, " BLOB NOT NULL)"
    );

	public static final String QUERY_CREATE_USER_PREFERENCE_MSSQL = StringUtils.join(
			"CREATE TABLE ", TABLE_USER_PREFERENCE,
			" (",COLUMN_APP_TYPE, " nVARCHAR(250) NOT NULL, ",
			COLUMN_APP_ID, " BIGINT NOT NULL, ",
			COLUMN_OWNER, " nVARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_DATE, " DATETIME, ",
			COLUMN_LAST_UPDATED_DATE, " DATETIME, ",
			"CONSTRAINT PK_PORTAL_USER_PREFERENCE PRIMARY KEY (",COLUMN_APP_ID,", ", COLUMN_APP_TYPE,", ", COLUMN_OWNER,"), ",
			COLUMN_USER_PREFERENCE, " VARBINARY(MAX) NOT NULL)"
	);

	public static final String QUERY_CREATE_USER_PREFERENCE_DB2 = StringUtils.join(
			"CREATE TABLE ", TABLE_USER_PREFERENCE,
			" (",COLUMN_APP_TYPE, " VARCHAR(250) NOT NULL, ",
			COLUMN_APP_ID, " DECIMAL(20) NOT NULL, ",
			COLUMN_OWNER, " VARCHAR(250) NOT NULL, ",
			COLUMN_CREATED_DATE, " TIMESTAMP (6), ",
			COLUMN_LAST_UPDATED_DATE, " TIMESTAMP (6), ",
			"CONSTRAINT PK_PORTAL_USER_PREFERENCE PRIMARY KEY (",COLUMN_APP_ID,", ", COLUMN_APP_TYPE,", ", COLUMN_OWNER,"), ",
			COLUMN_USER_PREFERENCE, " BLOB NOT NULL)"
	);
	
	public static final String SELECT_QUERY_TYPE = "SELECT";
	public static final String INSERT_QUERY_TYPE = "INSERT";
	public static final String UPDATE_QUERY_TYPE = "UPDATE";
	public static final String DELETE_QUERY_TYPE = "DELETE";
	public static final String SORT_ORDER_DESC = "DESC";
	
	public static final String NEGATION_LITERAL = "NOT";
	public static final String AND_LITERAL = " AND ";
	
	public static final String ORDER_BY_LITERAL = "ORDER BY ";
	public static final String WHERE_LITERAL = "WHERE ";
	
	public static final String SELECT_NEGATION_OPERATOR = " <> ?";
	public static final String SELECT_EQUALS_OPERATOR = " = ?";
	public static final String QUOTATION_OPERATOR = "?";
	
	public static final String SETTER_QUERY_KEY = "setterQuery";
	public static final String SETTER_QUERY_PARAM = "setterParams";
	
	public static final String TABLE_NAME_WILDCARD = "$TABLE_NAME$";
	public static final String PROJECTIONS_WILDCARD = "$PROJECTIONS$";
	public static final String FILTER_WILDCARD = "$FILTER$";
	public static final String SORT_WILDCARD = "$SORT$";
	public static final String SETTERS_WILDCARD = "$SETTERS$";
	public static final String PARAMS_WILDCARD = "$PARAMS$";
	
	public static final String COLUMN_USERS_APPLICATION_IND = "APPLICATION_IND";
	public static final String COLUMN_USERS_USER_NAME = "USER_NAME";
	public static final String COLUMN_USERS_FIRST_NAME = "FIRST_NAME";
	public static final String COLUMN_USERS_LAST_NAME = "LAST_NAME";
	public static final String COLUMN_USERS_EMAIL = "EMAIL";
	public static final String TABLE_REPOS_USERS = "C_REPOS_USER";
    public static final String TABLE_REPOS_DB_RELEASE = "C_REPOS_DB_RELEASE";
	public static final String COLUMN_LAST_CHANGE_DATE= "LAST_CHANGE_DATE";
	
}
