package com.informatica.mdm.portal.metadata.util;

public class PortalServiceConstants {
	
	public static final String CMX_APP_SERVER_TYPE = "cmx.appserver.type";
	public static final String JBOSS = "jboss";
	public static final String DATASOURCE_NAME_FORMAT = "jdbc/siperian-%s-ds";
	public static final String DATASOURCE_JBOSS_PREFIX = "java:jboss/datasources/";
	public static final String SIPERIAN = "siperian";
	public static final String SIPERIAN_HOME = "home";
	public static final String DATE_FORMAT = "yyyy-MM-dd HH:mm:ss";
	public static final String APPLICATION_DATE_FORMAT = "dd MMM yyyy HH:mm:ss";
	public static final String CMX_PROPERTIES = "resources/cmxserver.properties";
	public static final String AUTH_SECURITY_PAYLOAD = "X-MDM-AUTH-PAYLOAD";
	public static final String CONTENT_TYPE = "Content-Type";
	public static final String APPLICATION_JSON = "application/json";
	public static final String TRUSTED_APP = "infaPortal";
	public static final String HUB = "hub";
	public static final String CREATE_BE_URL = "%s/cmx/cs/%s/%s?systemName=%s";
	public static final String UPDATE_BE_URL = "%s/cmx/cs/%s/%s/%s?systemName=%s";
	public static final String UPDATE_BE_URL_PENDING = "%s/cmx/cs/%s/%s/%s?systemName=%s&interactionId=%s&recordState=PENDING";
	public static final String READ_BE_URL = "%s/cmx/cs/%s/%s/%s.json?readSystemFields=true&recordStates=ACTIVE,PENDING&depth=%s";
	public static final String PREVIEW_BE_URL = "%s/cmx/cs/%s/%s/%s.json?readSystemFields=true&recordStates=ACTIVE,PENDING&action=previewPromote&addFieldsToOriginal=true&interactionId=%s&depth=%s";
	public static final String CREATE_USER_URL = "%s/cmx/user";
	public static final String DELETE_USER_URL = "%s/cmx/user/%s";
	public static final String DELETE_BE_URL = "%s/cmx/cs/%s/%s/%s?systemName=%s";
	public static final String PORTAL_CONFIG = "portalConfig";
	public static final String RUNTIME_CONFIG = "runtimeConfig";
	public static final String FILE_NAME = "%s_%s.%s";
	public static final String JSON_EXT = "json";
	public static final String XML_EXT = "xml";
	public static final String BUNDLES_ZIP = "bundles.zip";
	public static final String ZIP_EXT = ".zip";
	public static final String LOCALE_FILE_FORMAT = "bundle_%s.properties";
	public static final String DEFAULT_BUNDLE_PROPETIES = "bundle.properties";
	public static final String BES_LOCALE = "selectedLocale=";
	public static final String PORTAL_LOCALE = "selectedLocale";
	public static final String LOCALE_KEY = "key";
	public static final String LOCALE_DISPLAY_NAME = "desc";
	public static final String DEFAULT_LOCALE = "en";
	public static final String CHANGE_PASSWORD_URL = "%s/cmx/user/password";
	public static final String CHANGEPASSWORD_OLD = "oldPassword";
	public static final String CHANGEPASSWORD_NEW = "newPassword";
	public static final String CHANGEPASSWORD_EMAIL = "userEmail";
	public static final String RESETPASSWORD_USERNAME = "username";
	public static final String RESETPASSWORD_URL = "resetPassword";
	public static final String RESETPASSWORD_URL_NEWUSER = "resetPasswordNewUser";
	public static final String CHANGEPASSWORD_LINKHASHVALUE = "ForgotPwdlinkHashValue";
	public static final String CHANGEPASSWORD_ISNEWUSER = "ChangePasswordIsNewUser";
	public static final String CHANGEPASSWORD_RESPONSE_STATUS = "Status";
	public static final String CHANGEPASSWORD_RESPONSE_EMAIL_STATUS = "Email Status";
	public static final String SET_PASSWORD_INVITATION = "setPassword";
    public static final String ADD_USER_SEND_EMAIL = "sendEmail";
    public static final String ADD_USER_IS_WORKFLOW = "isWorkflow";
	public final static String SEARCH_BE_URL = "%s/cmx/cs/%s/%s.json?action=query&recordStates=ACTIVE,PENDING&recordsToReturn=100&returnTotal=true&filter=%s='%s'%s";
	public final static String AND = "&";
	public final static String EQUALS = "=";
	public final static String CHILDREN = "children";
	public final static String DEPTH = "depth";
	public final static String ITEM = "item";
	public final static String COMA = ",";
	public final static String CURRENT_UID = "[CURRENT]";
	public final static String RUNTIME_CONFIG_CONFIGURATION = "configuration";
	public final static String RUNTIME_CONFIG_PASSWORD_SECTION = "Password Section";
	public final static String RUNTIME_CONFIG_PASSWORD_EXPIRY = "passwordResetLinkExpiry";
	public final static String RUNTIME_CONFIG_KEY = "key";
	public final static String RUNTIME_CONFIG_VALUE = "value";
	public final static String RUNTIME_CONFIG_TYPE = "type";
	public final static String RUNTIME_CONFIG_SESSION_TIMEOUT = "session.timeout";
	public static final String CHANGEPASSWORD_LINK_PROTOCOL = "http";
	public static final String HEADER_ATTRIBUTE_PORTAL_ID = "X-INFA-PORTALID";
	public final static String DOT = "\\.";
	public final static String RUNTIME_CONFIG_USERNAME = "username";
	public final static String EMAIL_LOGIN_NAME = "loginName";
	public final static String APP_SERVER_JBOSS = "jboss";
	public final static String APP_SERVER_WEBLOGIC = "weblogic";
	public final static String APP_SERVER_WEBSPHERE = "websphere";
	public final static String PORTAL_ASSC_DELTA_XML = "metadataxml/BuyerSide.change.xml";
	public final static String BE_RECORD_COUNT_ATTRIBUTE =  "recordCount";
	public final static String BE_NAME_BUYER_SIDE_ASDC =  "LookupInfaPortalAssociation";
	public static final String BE_DATA = "BEData";
	public final static String ROW_ID_OBJECT =  "rowidObject";
	public final static String HUB_STATE =  "hubStateInd";
	public final static String INTERRACTION_ID =  "interactionId";
	public final static String OBJECT =  "object";
	public final static String FIELD =  "field";
	public final static String NAME =  "name";
	public final static String DATATYPE =  "dataType";
	public final static String LOOKUP =  "lookup";
	public final static String KEY =  "key";
	public final static String ORIGINAL_KEY =  "$original";
	public final static String PORTAL_STATE =  "portalState";
	public static String BUILD_PROP = "/bin/build.properties";
	public static String USER_NAME = "userName";
	public static String FIRST_NAME = "firstName";
	public static String LAST_NAME = "lastName";
	public static String EMAIL = "email";
	public static final String USER_SESSION_ATTRIB ="UserSessionAttributes";
	public final static String MDM_CSRF_TOKEN_HEADER = "ICT";
	public final static String MDM_CSRF_TOKEN_CONFIG = "ict-config";
	public final static String FORGOT_PASSWORD_URL = "forgotPasswordUrl";
	public static final String SSO_ACS_URL = "%s/infa-portal/portals/login/saml/%s/%s";
	public static final String SP_METADAT_PREFIX = "GENERIC_PORTAL";
	public static final String SP_METADAT_DELIM = "_";
	public static final String SSO_CONFIG_SP_FILTER = "{\"name\": [\"%s\"]}";
	public static final String  PREFERENCE_TYPE = "PREFERENCE_TYPE";
    public static final String  PREFERENCE_TYPE_VALUE_MODEL = "ModelPreference";
    public static final String  PREFERENCE_PORTAL_CONFIG = "portalConfig";
	public static final String  PREFERENCE_PORTAL_VERSION = "version";
	public static final String  PREFERENCE_PORTAL_DB_CHANGE = "timeStamp";
	public static final String  PREFERENCE_PORTAL_LOCALE = "locale";
    public static final String  USER_PREFERENCE = "USER_PREFERENCE";
	
	
}
